### ISSUE TITLE
Database contains a non-string as map key: Uint16

### ISSUE THREAD

**Issue by sonicmouse** [maxmind/MaxMind-DB-Reader-dotnet#49]
Using this database:
```
{
  "BinaryFormatMajorVersion": 2,
  "BinaryFormatMinorVersion": 0,
  "BuildDate": "2018-08-07T23:25:47Z",
  "DatabaseType": "GeoLite2-City",
  "Description": {
    "en": "GeoLite2 City database"
  },
  "IPVersion": 6,
  "Languages": [
    "de",
    "en",
    "es",
    "fr",
    "ja",
    "pt-BR",
    "ru",
    "zh-CN"
  ]
}
```
When i call this in version 3.0.0 of MaxMind.GeoIP2 nuget package:
`using (var db = new DatabaseReader(_db.FullName)) { return db.City("216.206.142.2"); }`
I get this exception:

```
{MaxMind.Db.InvalidDatabaseException: Database contains a non-string as map key: Uint16
   at MaxMind.Db.Decoder.DecodeKey(Int64 offset, Int64& outOffset)
   at MaxMind.Db.Decoder.DecodeMapToType(Type expectedType, Int64 offset, Int32 size, Int64& outOffset, InjectableValues injectables)
   at MaxMind.Db.Decoder.DecodeByType(Type expectedType, ObjectType type, Int64 offset, Int32 size, Int64& outOffset, InjectableValues injectables)
   at MaxMind.Db.Decoder.DecodeByType(Type expectedType, ObjectType type, Int64 offset, Int32 size, Int64& outOffset, InjectableValues injectables)
   at MaxMind.Db.Decoder.Decode[T](Int64 offset, Int64& outOffset, InjectableValues injectables)
   at MaxMind.Db.Reader.ResolveDataPointer[T](Int32 pointer, InjectableValues injectables)
   at MaxMind.Db.Reader.Find[T](IPAddress ipAddress, Int32& prefixLength, InjectableValues injectables)
   at MaxMind.Db.Reader.Find[T](IPAddress ipAddress, InjectableValues injectables)
   at MaxMind.GeoIP2.DatabaseReader.Execute[T](String ipStr, IPAddress ipAddress, String type, Boolean throwOnNullResponse)
   at MaxMind.GeoIP2.DatabaseReader.City(IPAddress ipAddress)
   at LGPlayersService.Services.GeoIPDatabase.ResolveIPAddress(IPAddress ip)
```

This just started happening after I updated to the latest database

**Comment by oschwald** [comment]
It sounds like the database is corrupt. I would try downloading it again. Did you reopen the database reader after updating?

**Comment by sonicmouse** [comment]
bah -- that has to be it. It just tried it in the preprod environment and it works fine.

Sorry about that.
